/*----------------------------------------------------------
MASV: 21120456
HO TEN: Khưu Tấn Hoàng
LAB: 04
NGAY: 22/05/2024
----------------------------------------------------------*/
--//CAU LENH TAO DB
CREATE DATABASE QLSV
GO

USE QLSV
GO

/*----------------------------------------------------------
MASV: 21120456
HO TEN: Khưu Tấn Hoàng
LAB: 04
NGAY: 22/05/2024
----------------------------------------------------------*/
--//CAC CAU LENH TAO TABLE
CREATE TABLE SINHVIEN (
	MASV NVARCHAR(20) PRIMARY KEY,
	HOTEN NVARCHAR(100) NOT NULL,
	NGAYSINH DATETIME,
	DIACHI NVARCHAR(200),
	MALOP VARCHAR(20),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(MAX) NOT NULL
);
GO

CREATE TABLE NHANVIEN (
	MANV VARCHAR(20) PRIMARY KEY,
	HOTEN NVARCHAR(100) NOT NULL,
	EMAIL VARCHAR(20),
	LUONG VARBINARY(MAX),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(MAX) NOT NULL,
);
GO

CREATE TABLE LOP (
	MALOP VARCHAR(20) PRIMARY KEY,
	TENLOP NVARCHAR(100) NOT NULL,
	MANV VARCHAR(20)
);
GO

/*----------------------------------------------------------
MASV: 21120456
HO TEN: Khưu Tấn Hoàng
LAB: 04
NGAY: 22/05/2024
----------------------------------------------------------*/
-- // CAU LENH TAO STORED PROCEDURE
USE QLSV
GO

CREATE PROCEDURE SP_INS_ENCRYPT_SINHVIEN 
    @MASV NVARCHAR(20),
    @HOTEN NVARCHAR(100),
    @NGAYSINH DATETIME,
    @DIACHI NVARCHAR(200),
    @MALOP VARCHAR(20),
    @TENDN NVARCHAR(100),
    @MATKHAU VARCHAR(32) -- Đã được mã hóa sử dụng MD5
AS
BEGIN
    DECLARE @ENCRYPTED_PASSWORD VARBINARY(MAX);
    SET @ENCRYPTED_PASSWORD = CONVERT(VARBINARY(MAX), @MATKHAU, 2); -- Chuyển đổi từ chuỗi hex sang varbinary

    INSERT INTO SINHVIEN (MASV, HOTEN, NGAYSINH, DIACHI, MALOP, TENDN, MATKHAU)
    VALUES (@MASV, @HOTEN, @NGAYSINH, @DIACHI, @MALOP, @TENDN, @ENCRYPTED_PASSWORD);
END
GO

CREATE PROCEDURE SP_INS_ENCRYPT_NHANVIEN
    @MANV VARCHAR(20),
    @HOTEN NVARCHAR(100),
    @EMAIL VARCHAR(20),
    @LUONG VARCHAR(MAX),
    @TENDN NVARCHAR(100),
    @MATKHAU VARCHAR(MAX)
AS
BEGIN
	DECLARE @EncryptedSalary VARBINARY(MAX);
    SET @EncryptedSalary = CONVERT(VARBINARY(MAX), @LUONG, 2); -- Chuyển đổi từ chuỗi hex sang varbinary

    DECLARE @HashedPassword VARBINARY(MAX);
    SET @HashedPassword = CONVERT(VARBINARY(MAX), @MATKHAU, 2); -- Chuyển đổi từ chuỗi hex sang varbinary

	
    INSERT INTO NHANVIEN (MANV, HOTEN, EMAIL, LUONG, TENDN, MATKHAU)
    VALUES (@MANV, @HOTEN, @EMAIL, @EncryptedSalary, @TENDN, @HashedPassword);
END;
GO

CREATE PROCEDURE SP_SEL_ENCRYPT_NHANVIEN
AS
BEGIN
    SELECT MANV, HOTEN, EMAIL, LUONG AS LUONGCB
	FROM NHANVIEN
END;
GO